# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dcd989f4b262940844684c210c2b5a30c851f94a10b0e91c923b34af9d93e4b80c014911fe4ca0b0ea4aba6a63bb9d7de77674991946e788c78da312850d4b6

test:
  secret_key_base: 690ffc5b53a641dac71f68f84eec9defdb41b60dcacdc2f7efa6cfb49c78ff8e81883c58bbabf09615f220a723271f90b482431bdd2621042f826f7fa47435af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
